"""add tweet_sentiments table

Revision ID: add_tweet_sentiments
Revises: 55fae4214fb6
Create Date: 2026-04-20 14:19:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'add_tweet_sentiments'
down_revision: Union[str, Sequence[str], None] = '55fae4214fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet_sentiments',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('tweet_timestamp', sa.String(), nullable=False),
    sa.Column('sentiment', sa.Enum('bullish', 'bearish', 'neutral', name='sentimenttype'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('stock_tickers', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tweet_timestamp'], ['tweets.tweet_timestamp'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tweet_sentiments_tweet_timestamp'), 'tweet_sentiments', ['tweet_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tweet_sentiments_tweet_timestamp'), table_name='tweet_sentiments')
    op.drop_table('tweet_sentiments')
    # ### end Alembic commands ###
